keys:
  - &desktop_token B4383128C3A5F777CBDF1609DFE6E909801C9906
  - &server_hazel age135nzpugdahu0096cgld67gvylveqk63eqlvexc8jxd3clzs2g95sp08xyp
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *desktop_token
        age:
          - *server_hazel
