keys:
  - &desktop_token B4383128C3A5F777CBDF1609DFE6E909801C9906
  - &server_hazel age1na4qjmt7v5dh3k2vfjyp45zfx3zhhvdjh5z3jfyer6gcw04yed2s5r8phx
  - &server_oracle1 age1wvcu9typhu2s22e22qe96xd5q2skq0p78fe76j29ffu9lpjhzp6s7qvtfj
  - &server_bell age1s3zdl6gggq38zms04pk49zrq7ptk39cpzczxgedt5s35kv42xv5sqamasu
  - &server_greg age1ytw5hv3k50qnh6yn0ana3l932q7azkx0l2fg9zp9h02gknvqx4yq7yvcgl
  - &server_thomas age1556xjlmfp3nhhmv3md7k809vvyqru88q63a74e4576qxsvz99phqpfs5lj
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *desktop_token
        age:
          - *server_hazel
          - *server_oracle1
          - *server_bell
          - *server_greg
          - *server_thomas
