keys:
  - &desktop_token B4383128C3A5F777CBDF1609DFE6E909801C9906
  - &server_hazel $HAZEL_PUB
  - &server_oracle1 $ORACLE1_PUB
  - &server_bell $BELL_PUB
  - &server_greg $GREG_PUB
  - &server_thomas $THOMAS_PUB
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *desktop_token
        age:
          - *server_hazel
          - *server_oracle1
          - *server_bell
          - *server_greg
          - *server_thomas
